# This file tells Render how to deploy our app (it's called Blueprint)
services:
  - type: web
    name: n8n-rag-agent
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
    # The 'port' key must be placed at this level, not under envVars
    port: 5678
